---
- name: Configuring Apache Web Server
  hosts: node2
  tasks:
    - name: Install Apache Package
      yum:
        name: httpd
        state: present
    - name: Start Apache Service
      service:
        name: httpd
        state: started
    - name: Add Firewall Rules
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
    - name: Reload Firewall Configuration for the new rule
      systemd:
        name: firewalld
        state: reloaded
    - name: Copy Index file through Apache directory
      copy:
        src: index.html
        dest: /var/www/html/
    - name: Restart Apache Service
      service:
        name: httpd
        state: restarted
